id: PD64A1547
initial_creation_type: input
source_metadata:
  title: Nyala Pema Dündul Series
  language: fr
  description: 'Texts by and about the great siddha of Nyarong, Nyala Pema Dündul
    (nyag bla padma bdud ''dul, 1816–1872):'
  volume:
    bcbda4e7f1ea4f4c95386d493576352a:
      title: Advice Revealing How Our Faults Become Clear
      parent: Advice
    8f8ebb89ab3e4879bb7e3ce0afeb5bac:
      title: Advice on Abandoning the Eight Worldly Concerns
      parent: Advice
    7b6f8c667f9c49f3a2b25fb54f6e7e9b:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    304fbbc227284f3e97b944a05a82b348:
      title: Signs that the Common Preliminary Practices Have Penetrated the Mind
      parent: Advice
    71f869f876b943f295be91b48bcc47f0:
      title: Song of Advice for Giving Up Meat Eating
      parent: Advice
    9d2c83995ae348558707a62aa5a70091:
      title: The Heaven of Solitude
      parent: Advice
    0fb80bde7b964d609dce6914ec8e12ed:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Confession
    6c997325d99f47f997caf84a22197329:
      title: Dharmakāya Transference
      parent: Phowa
    e8de00c3ced347049d70a89d65f0d7dc:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
created_at: '2022-03-01T01:03:40.616937'
last_modified_at: '2022-03-01T01:03:40.616939'
